---
title: "ptcAssist source code"
# author: "Zhen Zhang"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output:
  html_document: 
    highlight: kate
    theme: readable
    toc: yes
    number_sections: false
---

<style type="text/css">
code.r{
  font-size: 15px;
}
</style>

### Frequentist
```{r, eval=FALSE,tidy=TRUE}
rm(list=ls())
nn <- length(ns <- c(20, 30))
nx <- length(xs <- c(0,3,5,10,15))
dfs <- data.frame(ncase=xs)
for(k in 1:nn){
  n <- ns[k]
  z <- numeric()
  df <- data.frame()
  for(i in 1:nx){
    x <- xs[i]
    y <- as.numeric(binom.test(x=x, n=n)$conf.int)
    df <- rbind( df, data.frame(n=n, orr=x/n, lower=y[1], upper=y[2]) )
  }
  dfs <- cbind(dfs, df)
}
# print(round(dfs,2), row.names=FALSE)
knitr::kable(dfs, digits=2, 
             caption = "\\label{tab:CPI}CP intervals.")
```

### Bayesian
```{r, eval=FALSE,tidy=TRUE}
a <- 1;  b <- 1  #shapes for Beta prior
r0 <- .25
r <- .6
cl <- .6 
nn <- length(ns <- c(20, 120))
nr <- length(rs <- seq(0,.35, by=.05))
dfs <- data.frame(ncase=round(ns[1]*rs))
for(k in 1:nn){
  n <- ns[k]
  z <- numeric()
  df <- data.frame()
  for(i in 1:nr){
    x <- round(n*rs[i])
    y <- qbeta(c((1-cl)/2, 1-(1-cl)/2), x+a, n-x+b)
    tmp <- data.frame(n=n, orr=x/n, lower=y[1], upper=y[2])
    if(k>1) tmp <- cbind(data.frame(ncase=x), tmp)
    df <- rbind( df, tmp)
  }
  dfs <- cbind(dfs, df)
}
# print(round(dfs,2), row.names=FALSE)
knitr::kable(dfs, digits=2, 
             caption = "\\label{tab:BI}Bayesian intervals.")

dfs <- data.frame()
for(sid in 1:2){
  if(sid==1){ x <- 0;  n <- 6;  r0 <- .25 }
  if(sid==2){ x <- 0;  n <- 10;  r0 <- .15 }
  pObs0 <- 100*pbinom(x,n,r0)
  pExceeds <- 100*(1-pbeta(r0, x+a, n-x+b))
  tmp <- data.frame(x=x, n=n, 'ORRpct'=100*r0, pObs0=pObs0, pExceeds=pExceeds)
  dfs <-rbind(dfs, tmp)
}
# print(round(dfs,1), row.names=FALSE)
knitr::kable(dfs, digits=1, 
             caption = "\\label{tab:BPP}Bayesian posterior probabilities.")
```
<a href="#top">Back to top</a>
